version: '3.9'

services:
  ubuntu_java:
    image: ubuntu_java
    container_name: ubuntu_java
    ports:
      - "9001:9001"
    build:
      context: .
      dockerfile: Dockerfile
   
    stdin_open: true
    tty: true
